/// <reference types="vite/client" />

interface ThreeGameDiagnostics {
  routingMode: 'link' | 'rotation';
  frame: number;
  elapsed: number;
  phase: 'ready' | 'wave' | 'paused' | 'won' | 'lost';
  stage: number;
  wave: number;
  money: number;
  lives: number;
  towers: number;
  enemies: number;
  projectiles: number;
  infusions: number;
  projectileInterceptions: number;
  layerOneEnemyHits: number;
  reactions: number;
  elementalStatuses: number;
  tintedEnemies: number;
  statusIcons: number;
  impactParticles: number;
  impactParticleBursts: number;
  draggingTower: boolean;
  pathRibbonMeshes: number;
  spawnDirectionMarkerCount: number;
  spawnDirectionError: number;
  spawnDirectionInView: boolean;
  spawnDirectionViewportX: number;
  spawnDirectionViewportY: number;
  tutorialHandVisible: boolean;
  tutorialHandMode: string;
  discoveryCueKind: '' | 'currency' | 'reaction' | 'nexus';
  discoveryCueVisible: boolean;
  discoveryCueHighlightOnly: boolean;
  discoveryCueTriggerCounts: Record<'currency' | 'reaction' | 'nexus', number>;
  maxTowerLayer: number;
  layerOneTowerCount: number;
  oppositeRaisedCellCount: number;
  oppositeRaisedTowerCount: number;
  maxLayerOneTowerLaneDistance: number;
  maxEnemyLayer: number;
  activeEnemyKinds: Array<'riftling' | 'runner' | 'brute' | 'wisp' | 'frostRay' | 'warder' | 'arcaneBulwark' | 'skyWarder' | 'colossus'>;
  maxStageEnemyLayer: number;
  maxBoardLayer: number;
  boardWidth: number;
  boardDepth: number;
  buildableCellCount: number;
  maxEnemyFacingError: number;
  maxEnemyLaneOffset: number;
  upcomingEnemyCount: number;
  upcomingEnemyKinds: Array<'riftling' | 'runner' | 'brute' | 'wisp' | 'frostRay' | 'warder' | 'arcaneBulwark' | 'skyWarder' | 'colossus'>;
  selectedWaveEnemyKind: 'riftling' | 'runner' | 'brute' | 'wisp' | 'frostRay' | 'warder' | 'arcaneBulwark' | 'skyWarder' | 'colossus' | null;
  inspectedBuildType: 'foundry' | 'fire' | 'ice' | 'wind' | 'earth' | 'amplifier' | 'lance' | null;
  unlockedTowers: number;
  connections: number;
  interactionMode: 'inspect' | 'build' | 'move' | 'link';
  selectedTowerId: number | null;
  selectedOutputAngle: number | null;
  linkSourceTowerId: number | null;
  towerLinks: Array<{
    sourceId: number;
    targetId: number;
    distance: number;
    range: number;
    facingError: number;
  }>;
  maxLinkedTowerFacingError: number;
  linkCandidates: Array<{
    towerId: number;
    valid: boolean;
    highlighted: boolean;
    reason: string;
  }>;
  lastLinkAttempt: {
    sourceId: number;
    targetId: number;
    result: string;
  } | null;
  towerConnectionRanges: Record<number, number>;
  towerBuffers: Record<number, number>;
  finiteAmmoTowerIds: number[];
  capacityBlockedTowerIds: number[];
  projectileLaunchesByTower: Record<number, number>;
  linkedProjectileLaunches: number;
  unlinkedProjectileLaunches: number;
  terminalBuffTowerIds: number[];
  terminalBuffProjectileLaunches: number;
  linkedSegmentEnemyHits: number;
  linkedSegmentDamage: number;
  linkGuideObjects: number;
  weaponAimGuideObjects: number;
  weaponAimGuideWidth: number;
  weaponAimGuideOpacity: number;
  projectileSpeedMultiplier: number;
  towerFireRateMultiplier: number;
  projectileCollisionRadius: number;
  projectileVisualScale: number;
  blocked: number;
  tutorialStep: number;
  tutorialObjective: string;
  tutorialHeadOnDot: number;
  tutorialDirectShots: number;
  reactionTutorialPopupVisible: boolean;
  elementalTintStrength: number;
  stageStartingMoney: number;
  killRewardMultiplier: number;
  enemyRewardMultiplier: number;
  waveClearRewardMultiplier: number;
  pathLength: number;
  pathPoints: Array<{ x: number; z: number }>;
  pathSegmentLengths: number[];
  pathGridAlignmentError: number;
  pathAxisAlignmentError: number;
  maxHorizontalPathSegment: number;
  maxVerticalPathSegment: number;
  waveCount: number;
  waveThreats: number[];
  waveEnemyCounts: number[];
  waveMaxEnemyLayers: number[];
  waveHealthMultipliers: number[];
  waveSpawnDensities: number[];
  waveSpawnWindows: number[];
  waveFlyingEnemyCounts: number[];
  waveBarrierEnemyCounts: number[];
  waveResistantEnemyCounts: number[];
  guidedTutorialComplete: boolean;
  tutorialMasteryPhase: boolean;
  masteryCheckpointCaptured: boolean;
  masteryCheckpointMoney: number | null;
  tutorialStartingLives: number;
  tutorialLeakDamage: number;
  masteryWaveCounts: number[];
  masteryWaveHealthMultipliers: number[];
  masteryWaveSpawnDensities: number[];
  masteryWaveThreats: number[];
  currentWaveHealthMultiplier: number;
  reactionMaxHpDamageRatio: number;
  lastReactionBonusDamage: number;
  activeReactionBarriers: number;
  activeArmoredEnemies: number;
  armoredRushingEnemies: number;
  visibleArmorShells: number;
  maxEnemySpeedMultiplier: number;
  visibleDetailedEnemies: number;
  activeEnemyMaxHp: number;
  lanceVfxCount: number;
  lanceVfxAnchorError: number;
  lanceVfxScaleError: number;
  explosionRadius: number;
  explosionHits: number;
  explosionDamage: number;
  explosionOutsideDamage: number;
  explosionOtherLayerDamage: number;
  explosionVisualRadius: number;
  explosionRingCount: number;
  explosionShardCount: number;
  explosionTargetCueCount: number;
  requiredTutorialTower: 'foundry' | 'amplifier' | 'lance' | null;
  lessonCell: { gx: number; gz: number } | null;
  lessonCellLaneDistance: number | null;
  enemySpeedMultiplier: number;
  lanceAmmoBarCount: number;
  lanceAmmoRatio: number;
  lanceFeederConnected: boolean;
  overlappingEnemyPairs: number;
  objectiveProgress: number;
  renderer: {
    calls: number;
    triangles: number;
    geometries: number;
    textures: number;
  };
  canvas: {
    clientWidth: number;
    clientHeight: number;
    width: number;
    height: number;
    dpr: number;
  };
}

interface ThreeGameTestHooks {
  seed(value: number): void;
  setState(name: 'active-play' | 'stress' | 'stage-two-ready' | 'stage-two-wave-three' | 'stage-two-wave-four' | 'stage-two-baseline-final' | 'stage-two-expanded-final' | 'stage-three-ready' | 'stage-three-final' | 'stage-three-final-active' | 'stage-three-baseline-late' | 'stage-three-expanded-late' | 'tutorial-link' | 'tutorial-rotation' | 'tutorial-ready' | 'tutorial-wave' | 'mastery-ready' | 'mastery-two-leaks' | 'mastery-fail' | 'mastery-baseline-final' | 'mastery-expanded-final' | 'terminal-flow' | 'status-fire' | 'status-reaction' | 'reaction-scaling' | 'armored-intact' | 'armored-break' | 'reward-stage-one' | 'reward-stage-two' | 'intro-currency' | 'intro-reaction' | 'intro-nexus' | 'explosion-vfx' | 'explosion-skill' | 'relay-lock' | 'fail' | 'win'): void;
  setPausedForScreenshot(paused: boolean): void;
  setReducedMotion(enabled: boolean): void;
  setSpeed(index: number): void;
  advance(seconds: number): void;
  hideDebugUi(hidden: boolean): void;
  getCellClientPoint(gx: number, gz: number): { x: number; y: number } | null;
  getTowerClientPoint(id: number): { x: number; y: number } | null;
}

interface Window {
  __THREE_GAME_DIAGNOSTICS__?: ThreeGameDiagnostics;
  __THREE_GAME_TEST_HOOKS__?: ThreeGameTestHooks;
}
